const propertyDetails = [
    {
        id: 1,
        name: "pAddress",
        title: "Property Address",
        type: "text",
        pHolder: "Enter property address",
    },
    {
        id: 2,
        name: "pType",
        title: "Property Type",
        type: "select",
        pHolder: "Select property type",
    },
    {
        id: 3,
        name: "noBd",
        title: "No. of Bedrooms",
        type: "number",
        pHolder: "",
    },
    {
        id: 4,
        name: "noS",
        title: "No. of Sitting Rooms",
        type: "number",
        pHolder: "",
    },
    {
        id: 5,
        name: "noK",
        title: "No. of Kitchens",
        type: "number",
        pHolder: "",
    },
    {
        id: 6,
        name: "noT",
        title: "No. of Toilets",
        type: "number",
        pHolder: "",
    },
    {
        id: 7,
        name: "noB",
        title: "No. of Bathrooms",
        type: "number",
        pHolder: "",
    },
    {
        id: 8,
        name: "pOwner",
        title: "Property Owner",
        type: "text",
        pHolder: "Enter name of property owner",
    },
    {
        id: 9,
        name: "validFrom",
        title: "valid From",
        type: "date",
        pHolder: "",
    },
    {
        id: 10,
        name: "validTo",
        title: "Valid To",
        type: "date",
        pHolder: "",
    },
    {
        id: 11,
        name: "price",
        title: "Price",
        type: "text",
        pHolder: "Enter the price of the property",
    },
    {
        id: 12,
        name: "pImage",
        title: "Property Image",
        type: "file",
        pHolder: "",
    },
    {
        id: 13,
        name: "desc",
        title: "Description",
        type: "textarea",
        pHolder: "Describe the property",
    }
]

export default propertyDetails;